name: CI/CD Pipeline
on: workflow_dispatch
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      IMAGE_NAME: "muhammedhamedelgaml/app_python"
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2


      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build and Push Docker image
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: true
      #     tags: $IMAGE_NAME:${{ github.run_number }}

      
      # - name: Ansible Deploy to Vagrant VMs
      #   uses: ansible/ansible-playbook-action@v2
      #   with:
      #     playbook: ansible/site.yml
      #     inventory: ansible/inventory
      #     extra_vars: |
      #       IMAGE=${{ env.IMAGE_NAME }}
      #       TAG=${{ github.run_number }}
      
      
  notify:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set Slack color
        id: set_color
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "SLACK_COLOR=good" >> $GITHUB_ENV
          elif [ "${{ job.status }}" == "failure" ]; then
            echo "SLACK_COLOR=danger" >> $GITHUB_ENV
          else
            echo "SLACK_COLOR=warning" >> $GITHUB_ENV
          fi

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel: '#cicdjenkins'
          text: |
            *${{ job.status }}:* Job ${{ github.repository }} build ${{ github.run_number }}
            For more info, visit: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_COLOR: ${{ env.SLACK_COLOR }}
